# Audio Wizard {#Majestic-Sound}

### Keywords

Music, Audiophile

## The Revolution

What makes a pop song, or any song, popular and successful? Songs that are popular are catchy, unique, and tap into the unconscious mind. When you hear a pop song for the first time, you generally know who the performer is, think Taylor Swift or Justin Bieber. But how do listeners unconsciously recognize performers? How much significance is placed on the beat, melody, or genre? Audio Wizard looks to discover this relationship and help produce the best music. 

In the beginning discovering artists who are relatively unknown would be the most efficient to control costs. As the algorithm grows to become more complex and gain recognition, voice signatures will become an input and the melody, beat, and dynamics will generate on their own. Mainstream artists will want to team up with Audio Wizard. This will allow us to be in a strong position for negotiations.

## The Art of Sound

The first step is to take songs that have been popular for years and dissect the underlying attributes of the song. This includes the tones, beat, melody, vocals, and instruments.
We would segment our analysis based on one genre at first with the largest data sample. We know that different genres will have different characteristics that make them popular.
We will find correlations between the songs within that genre and begin to build out a model to predict success for that specific genre. 
We expect that the melody or the beat is the strongest predictor of popularity, with the the voice and notes of the singer being significant but to a lesser extent.
A powerful confounding variable is star power. Too often songs are popular just because they are sung by a mainstream artist who is established with star power. We want to try to minimize this to ensure no matter the song we want a record that will go platinum and be successful. 

Tones and sound can be broken down based on frequency of vibrations.

Our algorithm will scan through submissions from artists to match the right voice to the sound. The artist will work with producers to develop the best lyrical delivery of the song.

We will also analyze multiple genres and find ways to fuse genres to create new sounds that will galvanize listeners. This is similar to how techno and EDM are now fusing with pop culture to become more mainstream. 

## The Future.

Audio Wizard looks to help build songs that will be enjoyed by everyone. The goal is to build music in whatever genre to appeal to the masses. A limitation we will need to address is building songs that sound "generic" or too similar to the last song. In order to combat this, we need to build our algorithm to prevent certain tones to ensure uniqueness. Risks will be measured with a proven algorithm to help producers make the best music and it will also eliminate the unnecessary risks associated to an investment into a album production. Music is very subjective and that will be one of the biggest challenges for Audio Wizard. There are so many variables outside the production process that can be considered, but we have to start somewhere. Audio Wizard will redefine the bar of making music and build songs that will be celebrated.
