# Balance Temple {#Your Body is a Temple}

#### Body, Mind, Health, Fitness, Pain-Free

## Sedentary.

How did you get into that state of physical pain? If the answer is not external factors, the pain is probably only caused by you! Having good fundamental movements is essential for humans to be healthy. Fundamental movements require a balance of multiple areas of the body to work together. However, in today's digital age, more and more jobs are becoming sedentary. When your body does not have good fundamental balance, muscle groups begin to compensate for one another, often leading to pain and maybe even surgery down the line. Balance Temple looks to help everyday people who care about their health by providing data on muscle groups that need improvement and providing rehabiliation exercises to help people achieve balance.

Balance Temple's primary focus is lower back pain, the most common pain faced by working adults. Too often, adults will continue day after day, year after year, with the same lingering pain without trying to make it better. Quick fixes (pain pills or chiropracty) don't address the root of the problem.
Now, Balance Temple gives people access to the information they seek about their back pain and how to solve it.

## Pain Points.

First, we will build a sensor that an individual can strap to their body so their movements can be tracked. The software embedded in the sensor would measure detailed information about the stress on individual muscle groups to discover muscle groups that are overcompensating or in pain. Balance Temple will also use demographic and health variables such as age, weight, height, ethnicity, etc. Over time, Balance Temple would learn the user's movements and provide exercises to improve weak areas. In extreme cases, Balance Temple would recommend the user to a physician before more serious problems occur.  

To maximize the benefit of Balance Temple, users must wear it during rehab exercises to monitoring their progress. Over time, through many iterations, Balance Temple will begin to prescribe specific exercises depending on the stress levels of different muscles. Exercises will be targeted to also strengthen other areas of weakness but will focus on the specific pain point. Eventually, Balance Temple will be so efficient that at any stage of recovery, there will be specific targeted exercises. Balance Temple will be able to learn all different types of human body characteristics and be able to dissect specific exercises that are more beneficial for a specific body type.  

## Pain Relief.

Balance Temple will always look for other areas of improvement because the human body can never achieve perfect balance. In future products, Balance Temple can be trained to address other kinds of body pain beyond back pain.

Balance Temple will help individuals get ahead of the curve and help their own body. Consumers would use Balance Temple to be proactive about their health. However, the task is extremely challenging and costly. Developing a device to track human movement to the precision required to measure muscle stress will be difficult. Furthermore, individuals using Balance Temple need to be aware that getting healthier is a process that requires effort and repetition. With that said, once an individual is committed, the foundation will be set. Balance Temple will help people recover from lingering pains, be less injury prone, and ultimately live a healthier life.


